### ISSUE TITLE
No voicemail in iOS app

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/mattermost-ios-classic#56]
In android user can record a voicemail to another user straight forward but this is not possible in the iOS app and you cant even attach a voice recording from the voice recorder library?

**Comment by jasonblais** [comment]
Thanks @kaksikanaa , appreciate your feedback.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by lindy65** [comment]
Hi @kaksikanaa,

We haven't received an update so I'll close this issue off for now. Please consider [contributing this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) :)
