### ISSUE TITLE
No image management features

### ISSUE THREAD

**Issue by fmp777** [mattermost/mattermost-ios-classic#60]
When an image is shared in the app, you can't "download" it to the device library, nor copy, nor share.  This might be considered a feature request, but in today's standards, is likely better classified as a bug.

**Comment by lindy65** [comment]
Thanks @fmp777, appreciate your feedback.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by lindy65** [comment]
Hi @fmp777, we haven't received an update so we'll assume you've opened a request on the feature idea forum.

I'll close this issue off here for now.
